Add support to retrieve environment variable
aztfmod/terraform-provider-azurecaf pull request #202
Opened 2022-10-31 16:16 UTC by LaurentLesle

## PR Checklist

---

- [ ] I have read the [CONTRIBUTING.MD instructions](./CONTRIBUTING.md)
- [ ] I have changed the `resourceDefinition.json`
- [ ] I have generated the resource model (there's a ```models_generated.go``` file in my PR)
- [ ] I have updated the [README.md#resource-status](../README.md)
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Add support to retrieve an environment variable

```hcl
data "azurecaf_environment_variable" "PAT" {
    name           = "PAT_TOKEN"
    fails_if_empty = true
    sensitive      = true
}
```

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Testing

2022-11-01 02:40 UTC, arnaudlh requested changes

2022-11-01 02:40 UTC, arnaudlh commented on docs/data-sources/azurecaf_environment_variable.md
> +* fails_if_empty (optional) - Through an error if the environment variable is not set (default: false).
```suggestion
* fails_if_empty (optional) - Throws an error if the environment variable is not set (default: false).
```

2022-11-01 02:40 UTC, arnaudlh commented on docs/data-sources/azurecaf_environment_variable.md
> +# Retreive the PAT_TOKEN variable as a sensitive data and through an error if it does not exist.
```suggestion
# Retrieve the PAT_TOKEN variable as a sensitive data and through an error if it does not exist.
```

2022-11-01 02:40 UTC, arnaudlh commented on azurecaf/data_environment_variable.go
> +				Description: "Through an error if the environment variable is not set (default: false).",
```suggestion
				Description: "Throws an error if the environment variable is not set (default: false).",
```

2022-11-01 02:55 UTC, arnaudlh approved these changes
LGTM

2022-11-01 08:40 UTC, merged

2022-11-16 08:56 UTC, BzSpi commented
Do you have any example of use case for this feature ? I'm curious :)